### ISSUE TITLE
TypeError: onMessageReceived() takes exactly 7 arguments (8 given)

### ISSUE THREAD

**Issue by thinko** [stenyak/breakbot#5] opened 2013-08-30 20:34 UTC
I get the following error occasionally, and am trying to figure out what parameters are being passed that the receiving function accepts less arguments.

ReaderThread:   Waiting, time to die: T-180 seconds
2013-08-30 14:05:32.738514 EE catch_them_all.py:12:
Traceback (most recent call last):
  File "/home/whatsapp/breakbot-master/catch_them_all.py", line 10, in wrapper
    return function(_args, *_kwargs)
TypeError: onMessageReceived() takes exactly 7 arguments (8 given)

2013-08-30 14:05:32.738514 EE catch_them_all.py:12: Exception in function onMessageReceived

**Comment by stenyak** [comment] 2013-08-30 21:15
I just pushed a new version of breakbot and yowsup, it should be fixed since 838d98005c93f1fb4781135c4b24dbd6e29cb65e.

Please pull the newest version and let me know if the problem is fixed.

Thanks for the report!

**Comment by stenyak** [comment] 2013-09-06 20:07
Marked as fixed. Please let me know if the bug persists.

**Closed as completed by stenyak** 2013-09-06 20:07 UTC
Labels: bug
